server:
  port: 8989
  context-path: /comm-mapper
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: hr
    username: hr
    driver-class-name: oracle.jdbc.OracleDriver
mybatis:
  type-aliases-package: com.baizhi.entity